apiVersion: v1
kind: ConfigMap
metadata:
  name: menus-backend-config
  namespace: apptolast-menus-prod
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8080"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
  SPRING_FLYWAY_ENABLED: "true"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics"
